//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KB_mojuWeibao
    {
        public int byID { get; set; }
        public Nullable<int> mjID { get; set; }
        public string mojuName { get; set; }
        public Nullable<int> mojuNub { get; set; }
        public Nullable<int> liftNub { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<System.DateTime> boayangTime { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> userID { get; set; }
        public string userName { get; set; }
    }
}
