//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KB_Model
    {
        public int modelID { get; set; }
        public Nullable<decimal> intervalTime { get; set; }
        public Nullable<decimal> ChangeTime { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> plcListID { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public Nullable<int> PLC_modelID { get; set; }
    }
}
