//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KB_PLC_guding
    {
        public int GID { get; set; }
        public Nullable<int> plcID { get; set; }
        public string sname { get; set; }
        public string plc_address { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public string plc_addressType { get; set; }
        public Nullable<int> addressLenth { get; set; }
    }
}
