//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class easyYJEntities : DbContext
    {
        public easyYJEntities()
            : base("name=easyYJEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KB_cangKu> KB_cangKu { get; set; }
        public virtual DbSet<KB_cangKuIn> KB_cangKuIn { get; set; }
        public virtual DbSet<KB_cangKuOut> KB_cangKuOut { get; set; }
        public virtual DbSet<KB_cangKuSY> KB_cangKuSY { get; set; }
        public virtual DbSet<KB_DataSave> KB_DataSave { get; set; }
        public virtual DbSet<KB_Model> KB_Model { get; set; }
        public virtual DbSet<KB_moju> KB_moju { get; set; }
        public virtual DbSet<KB_mojuModel> KB_mojuModel { get; set; }
        public virtual DbSet<KB_mojuWeibao> KB_mojuWeibao { get; set; }
        public virtual DbSet<KB_PLC_guding> KB_PLC_guding { get; set; }
        public virtual DbSet<KB_ProductionPlan> KB_ProductionPlan { get; set; }
        public virtual DbSet<KB_Shift> KB_Shift { get; set; }
        public virtual DbSet<YJ_LogALL> YJ_LogALL { get; set; }
        public virtual DbSet<YJ_Manage> YJ_Manage { get; set; }
        public virtual DbSet<YJ_ManageChuli> YJ_ManageChuli { get; set; }
        public virtual DbSet<YJ_ManageSend> YJ_ManageSend { get; set; }
        public virtual DbSet<YJ_ManageUser> YJ_ManageUser { get; set; }
        public virtual DbSet<YJ_Menu> YJ_Menu { get; set; }
        public virtual DbSet<YJ_PLC> YJ_PLC { get; set; }
        public virtual DbSet<YJ_PLC_linkLog> YJ_PLC_linkLog { get; set; }
        public virtual DbSet<YJ_PLC_list> YJ_PLC_list { get; set; }
        public virtual DbSet<YJ_PLC_log> YJ_PLC_log { get; set; }
        public virtual DbSet<YJ_Product> YJ_Product { get; set; }
        public virtual DbSet<YJ_ProductLog> YJ_ProductLog { get; set; }
        public virtual DbSet<YJ_ProductXiaohao> YJ_ProductXiaohao { get; set; }
        public virtual DbSet<YJ_User> YJ_User { get; set; }
        public virtual DbSet<YJ_PLC_list_updateLog> YJ_PLC_list_updateLog { get; set; }
    }
}
