//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class YJ_ProductXiaohao
    {
        public int proXHID { get; set; }
        public Nullable<int> proID { get; set; }
        public Nullable<int> plcListID { get; set; }
        public Nullable<int> xiaohao { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public Nullable<System.DateTime> createtTime { get; set; }
    }
}
