//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class YJ_PLC_list_updateLog
    {
        public int plcListID { get; set; }
        public Nullable<int> plcID { get; set; }
        public string PLC_adress { get; set; }
        public string PLC_addressType { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> addressLenth { get; set; }
        public Nullable<int> proID { get; set; }
        public Nullable<int> chufa { get; set; }
        public string shuju_u { get; set; }
        public string where_PLC_addressType { get; set; }
        public string where_PLC_address { get; set; }
        public string where_tiaojian { get; set; }
        public string where_content { get; set; }
        public string returnVal { get; set; }
        public string chuli { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public Nullable<int> where_returnVal { get; set; }
    }
}
