//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class YJ_ProductLog
    {
        public int proLogID { get; set; }
        public Nullable<int> proID { get; set; }
        public string proName { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public Nullable<int> lifeValue { get; set; }
        public string unit { get; set; }
        public Nullable<int> yujingValue { get; set; }
        public Nullable<int> DValue { get; set; }
        public Nullable<int> shopTime { get; set; }
        public Nullable<int> menuID { get; set; }
        public string imgPath { get; set; }
        public string shopTimeType { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> updateTimeW { get; set; }
        public Nullable<System.DateTime> yujing_sendTime { get; set; }
        public Nullable<System.DateTime> baojing_sendTime { get; set; }
        public string upType { get; set; }
        public Nullable<System.DateTime> upTime { get; set; }
        public Nullable<int> MID { get; set; }
    }
}
