//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class YJ_User
    {
        public int userID { get; set; }
        public string userName { get; set; }
        public string mobile { get; set; }
        public string Email { get; set; }
        public string password { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public Nullable<int> userType { get; set; }
    }
}
